### ISSUE TITLE
Changed behaviour, broken tests

### ISSUE THREAD

**Issue by kyranjamie** [bitcoinerlab/secp256k1#4]
Just a heads up incase unintentional, [the `1.0.4` upgrade broke our bip322 tests found here](https://github.com/hirosystems/wallet/blob/2b4a2a9b94507d4a0f7ae9b46ecfe0a335c9e2f8/src/shared/crypto/bitcoin/bip322/sign-message-bip322.spec.ts)

**Comment by landabaso** [comment]
Thank you for your feedback.

The intention of this library is to adhere to the specifications outlined by `bitcoinjs-lib` for `secp256k1`. Nonetheless, [it was highlighted that there was a discrepancy with these specs](https://github.com/bitcoinerlab/secp256k1/issues/3) regarding Schnorr signatures. Since the specifications were not being strictly followed anyway, the decision was made to use random data when `auxRand` wasn't provided.

Given that `bitcoinjs-lib` is [transitioning to default to all-zero Buffers for `auxRand`](https://github.com/bitcoinjs/tiny-secp256k1/issues/118) (which mirrors the original configuration of this library), it seems appropriate to revert to this approach.

**Comment by landabaso** [comment]
The newly released version v1.0.5 has now reverted to using an all-zero Buffer for `auxRand` when it isn't provided. This should align with the recent changes in `bitcoinjs-lib` and address the issues you encountered in your `bip322` tests.

Please update to v1.0.5 and confirm whether the issue has been resolved.

This issue will now be closed, given the changes implemented. If you still encounter any problems, feel free to reopen it or create a new one. Thank you again for your input.
